# https://dart.dev/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    [example/**]

linter:
  rules:
    - prefer_single_quotes
    - directives_ordering
    - sort_pub_dependencies
    - unnecessary_parenthesis
    - always_declare_return_types
    - prefer_relative_imports