name: hors
description: A simple Dart package to extract date and time from Russian texts.
version: 0.9.0
# repository: –

environment:
  sdk: '>=2.17.2 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
