name: hors
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: –

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
