name: cli
description: An example of Hors library.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  hors:
    path: ../..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
